# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8434795dcd2d53c7c9a9a809ecedb8c2bce00e867ecae8136528749ff5432a0f4df8a64702af80a765b3ff37e9e1bfa1330856ec92f28974941281276fbc5877

test:
  secret_key_base: 071ae0aa01d419d053bd0f9e1342fd831fb96b9d8a53a2120391a5421ab39cb81263f221e2c106ce0ef48910494b6956016ab561b5b508eb851408e5f8dea03d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
